const {
  fetchAllCategoryData,
  fetchAllReviewData,
  fetchReviewById,
  fetchCommentsByReviewId,
} = require("../models/categoryDataModel");
const app = require("../app");

exports.getCategoryData = (req, res, next) => {
  fetchAllCategoryData()
    .then((categories) => {
      res.status(200).send({ categories });
    })
    .catch((err) => {
      next(err);
    });
};

exports.getReviewData = (req, res, next) => {
  fetchAllReviewData()
    .then((reviews) => {
      res.status(200).send({ reviews });
    })
    .catch((err) => {
      next(err);
    });
};

exports.getReviewById = (req, res, next) => {
  const { review_id } = req.params;
  fetchReviewById(review_id)
    .then((review) => {
      res.status(200).send({ review });
    })
    .catch((err) => {
      next(err);
    });
};
/*
currently in main.
resubmitted a pr for branch 6, not yet merged
started branch 7 but stashed all code
to do...
get branch 6 feedback and merge to main
continue with 7
submit pr and merge with main and solve conflicts
*/

exports.getCommentsByReviewId = (req, res, next) => {
  const { review_id } = req.params;
  fetchCommentsByReviewId(review_id)
    .then((comments) => {
      res.status(200).send({ comments });
    })
    .catch((err) => {
      if (err.status === 404) {
        res.status(200).send({ comments: [] });
      } else {
        next(err);
      }
    });
};
